application: passesforlatemeal
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: Images
- url: /bootstrap
  static_dir: bootstrap
- url: /.*
  script: pflm.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest